In [1]:
import pandas as pd
import numpy as np
import glob

# 1. 파일 불러오기
pitcher_files = sorted(glob.glob("../kbodata_output/pitchers_20*.csv"))
scoreboard_files = sorted(glob.glob("../kbodata_output/scoreboards_20*.csv"))

pitchers = pd.concat([pd.read_csv(f) for f in pitcher_files], ignore_index=True)
scoreboards = pd.concat([pd.read_csv(f) for f in scoreboard_files], ignore_index=True)

# 2. 연도 정보 붙이기 (예: pitchers_2023.csv → 2023)
def extract_year_from_filename(path):
    return int(path.split("_")[-1].split(".")[0])

for f in pitcher_files:
    year = extract_year_from_filename(f)
    df = pd.read_csv(f)
    df["year"] = year
    pitchers = pd.concat([pitchers, df], ignore_index=True)

for f in scoreboard_files:
    year = extract_year_from_filename(f)
    df = pd.read_csv(f)
    df["year"] = year
    scoreboards = pd.concat([scoreboards, df], ignore_index=True)

In [2]:
import pandas as pd

# 1. 전처리: 이닝 문자열을 float으로 변환하는 함수
def convert_inning_str_to_float(s):
    try:
        s = str(s).zfill(2)
        full = int(s[:-1])
        partial = int(s[-1])
        return full + {0: 0.0, 1: 1/3, 2: 2/3}.get(partial, 0)
    except:
        return 0

# 2. IP 컬럼 생성
pitchers["IP"] = pitchers["inning"].apply(convert_inning_str_to_float)

# 3. RS 계산용 함수
def get_inning_range(ip_float):
    full = int(ip_float)
    partial = ip_float - full
    innings = list(range(1, full + 1))
    if partial >= 1/3:
        innings.append(full + 1)
    return innings

def calculate_rs(pitcher_df, scoreboard_df):
    rs_list = []
    for _, row in pitcher_df.iterrows():
        idx = row["idx"]
        team = row["team"]
        ip = row["IP"]

        innings = get_inning_range(ip)
        sb_row = scoreboard_df[scoreboard_df["idx"] == idx]
        if sb_row.empty:
            rs_list.append(None)
            continue

        sb = sb_row.iloc[0]
        team_name = team.strip()
        home = sb["home"].strip()
        away = sb["away"].strip()

        # 홈/원정 여부는 고려하지 않고 전체 득점으로 계산
        scores = []
        for i in innings:
            col = f"i_{i}"
            try:
                val = int(sb[col]) if sb[col] != "-" else 0
            except:
                val = 0
            scores.append(val)
        rs_list.append(sum(scores))
    pitcher_df["RS"] = rs_list
    return pitcher_df

# 4. RS 계산
pitchers_with_ip = pitchers[pitchers["IP"] > 0]
pitchers_with_rs = calculate_rs(pitchers_with_ip, scoreboards)

# 5. 시즌별 요약 테이블 생성
season_stats = pitchers_with_rs.groupby(["name", "year"]).agg({
    "IP": "sum",
    "RS": "sum",
    "result": lambda x: (x == "W").sum()  # 승수 계산
}).reset_index()

derived_stats = pitchers_with_rs.groupby(["name", "year"]).agg({
    "strikeout": "sum",
    "dead4ball": "sum",
    "earnedrun": "sum",
    "hitted": "sum",
    "homerun": "sum"
}).reset_index()

# 6. 파생 변수 계산
season_stats = pd.merge(season_stats, derived_stats, on=["name", "year"])

season_stats = season_stats.rename(columns={"result": "W"})

season_stats["ERA"] = season_stats["earnedrun"] * 9 / season_stats["IP"]
season_stats["WHIP"] = (season_stats["hitted"] + season_stats["dead4ball"]) / season_stats["IP"]
season_stats["FIP"] = (13 * season_stats["homerun"] + 3 * season_stats["dead4ball"] - 2 * season_stats["strikeout"]) / season_stats["IP"] + 3.2
season_stats["K9"] = season_stats["strikeout"] * 9 / season_stats["IP"]
season_stats["BB9"] = season_stats["dead4ball"] * 9 / season_stats["IP"]

# 8. 불필요한 컬럼 제거
season_stats = season_stats.drop(columns=["strikeout", "dead4ball", "earnedrun", "hitted", "homerun"])

# 9. 최종 확인
import seaborn as sns
import matplotlib.pyplot as plt

display(season_stats.head())

/var/folders/48/s46fmd9166lflhx4v40_hps80000gn/T/ipykernel_10999/220778849.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pitcher_df["RS"] = rs_list

,name,year,IP,RS,W,ERA,WHIP,FIP,K9,BB9
0,0,2012,12.000000,14,2,1.500000,0.666667,5.200000,3.000000,1.500000
1,가뇽,2020,319.333333,160,22,4.340292,1.471816,3.375365,7.947808,4.114823
2,가득염,2008,65.333333,56,8,3.857143,1.224490,3.842857,6.612245,2.755102
3,가득염,2009,16.000000,20,0,4.500000,1.250000,5.575000,3.375000,4.500000
4,가득염,2010,41.333333,24,0,4.354839,1.258065,4.216129,6.967742,3.919355

In [3]:
season_stats[season_stats["name"] == "문동주"].sort_values("year")

,name,year,IP,RS,W,ERA,WHIP,FIP,K9,BB9
1018,문동주,2022,57.333333,34,2,5.651163,1.500000,4.525581,11.302326,4.709302
1019,문동주,2023,251.333333,140,16,3.652520,1.344828,3.383024,7.591512,3.437666

In [4]:
import pandas as pd

# 1. player_info_sample.csv 불러오기
player_info = pd.read_csv("../player_info_main.csv")

# 2. 컬럼명 통일 (병합을 위해)
player_info = player_info.rename(columns={
    "player_name": "name",
    "season": "year"
})

# 3. year 컬럼을 정수형으로 변환
player_info["year"] = player_info["year"].astype(int)
season_stats["year"] = season_stats["year"].astype(int)

# 4. 두 데이터프레임 병합
merged_df = pd.merge(season_stats, player_info, on=["name", "year"], how="inner")

# 5. 결과 확인
# 병합된 데이터 상위 10개만 확인
print(merged_df.head(10))

  name  year          IP   RS   W       ERA      WHIP       FIP        K9  \
0  고영표  2017  303.333333  146  16  4.806593  1.424176  3.331868  7.714286
1  고영표  2018  302.000000  180  14  5.006623  1.496689  3.577483  8.463576
2  고영표  2021  359.333333  228  22  2.955473  1.135436  2.966234  7.063080
3  고영표  2022  384.000000  162  26  3.328125  1.276042  2.663542  7.593750
4  고영표  2023  387.333333  170  26  2.834768  1.218589  2.885026  5.901893
5  고원준  2010  262.000000  114  10  4.122137  1.496183  5.032061  5.977099
6  고원준  2012  226.000000   86   8  4.300885  1.672566  4.961062  4.300885
7  고원준  2013  103.333333   44   2  5.574194  1.741935  4.651613  4.529032
8   곽빈  2021  226.000000  100   8  4.141593  1.672566  4.651327  8.681416
9   곽빈  2022  306.000000  114  16  3.705882  1.450980  3.912418  8.294118

        BB9 salary_next  fa  age
0  2.195604       5,200   0   27
1  2.384106      11,500   0   28
2  2.053803      30,000   0   29
3  1.828125      43,000   0   30
4  1.580034     200,000   0   31
5  5.015267       2,400   0   21
6  4.699115      11,000   0   23
7  4.354839       9,000   0   24
8  7.725664       3,000   0   23
9  4.352941       6,500   0   24

In [5]:
# 기존 테이블을 복사 (원본 유지)
df_log = merged_df.copy()

# 'salary_next' 컬럼을 정수형으로 처리하고 로그 변환
df_log["salary_next_won"] = (
    df_log["salary_next"]
    .astype(str)
    .str.replace(",", "")
    .astype(float) * 10000
)

# 로그 변환된 컬럼 추가
import numpy as np
df_log["log_salary_next"] = np.log1p(df_log["salary_next_won"])

# ✅ 연도 더미 변수 생성 (year 컬럼 기준)
df_log = pd.get_dummies(df_log, columns=["year"], prefix="year", drop_first=True)

# 결과 확인
print(df_log.head())

  name          IP   RS   W       ERA      WHIP       FIP        K9       BB9  \
0  고영표  303.333333  146  16  4.806593  1.424176  3.331868  7.714286  2.195604
1  고영표  302.000000  180  14  5.006623  1.496689  3.577483  8.463576  2.384106
2  고영표  359.333333  228  22  2.955473  1.135436  2.966234  7.063080  2.053803
3  고영표  384.000000  162  26  3.328125  1.276042  2.663542  7.593750  1.828125
4  고영표  387.333333  170  26  2.834768  1.218589  2.885026  5.901893  1.580034

  salary_next  ...  year_2014  year_2015  year_2016  year_2017  year_2018  \
0       5,200  ...      False      False      False       True      False
1      11,500  ...      False      False      False      False       True
2      30,000  ...      False      False      False      False      False
3      43,000  ...      False      False      False      False      False
4     200,000  ...      False      False      False      False      False

   year_2019  year_2020  year_2021  year_2022  year_2023
0      False      False      False      False      False
1      False      False      False      False      False
2      False      False       True      False      False
3      False      False      False       True      False
4      False      False      False      False       True

[5 rows x 28 columns]

# 잔차 구하기

In [7]:
import statsmodels.api as sm

features_step1 = ["RS", "ERA", "IP"] + [col for col in df_log.columns if col.startswith("year_")]
X_step1 = sm.add_constant(df_log[features_step1])
y_step1 = df_log["W"]

valid_idx = X_step1.notnull().all(axis=1) & y_step1.notnull()
X_valid1 = X_step1.loc[valid_idx].astype(float)
y_valid1 = y_step1.loc[valid_idx].astype(float)

model_step1 = sm.OLS(y_valid1, X_valid1).fit()
df_log.loc[valid_idx, "resid_W"] = model_step1.resid  # ✨ 여기서 잔차 컬럼 추가!

In [8]:
print(model_step1.resid)

0      0.345364
1     -4.499043
2     -4.773351
3      4.562043
4      3.597199
         ...
292    3.732868
293   -1.846304
294    2.240120
295    3.957464
296    1.121162
Length: 297, dtype: float64

# 잔차 넣고 OLS 회귀식

In [9]:
features_step2 = [
    "resid_W", "ERA", "IP", "K9", "BB9", "WHIP", "FIP", "age", "fa"
] + [col for col in df_log.columns if col.startswith("year_")]

X_step2 = sm.add_constant(df_log[features_step2])
y_step2 = df_log["log_salary_next"]

valid_idx = X_step2.notnull().all(axis=1) & y_step2.notnull()
X_valid2 = X_step2.loc[valid_idx].astype(float)
y_valid2 = y_step2.loc[valid_idx].astype(float)

model_step2 = sm.OLS(y_valid2, X_valid2).fit()
print(model_step2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        log_salary_next   R-squared:                       0.476
Model:                            OLS   Adj. R-squared:                  0.432
Method:                 Least Squares   F-statistic:                     10.80
Date:                Fri, 13 Jun 2025   Prob (F-statistic):           6.66e-27
Time:                        01:09:14   Log-Likelihood:                -323.18
No. Observations:                 297   AIC:                             694.4
Df Residuals:                     273   BIC:                             783.0
Df Model:                          23
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         14.7126      0.784     18.770      0.000      13.169      16.256
resid_W        0.0218      0.012      1.865      0.063      -0.001       0.045
ERA            0.0688      0.060      1.155      0.249      -0.048       0.186
IP             0.0041      0.001      7.422      0.000       0.003       0.005
K9             0.0251      0.038      0.652      0.515      -0.051       0.101
BB9           -0.0496      0.048     -1.032      0.303      -0.144       0.045
WHIP           0.0622      0.361      0.172      0.863      -0.648       0.773
FIP           -0.1273      0.089     -1.427      0.155      -0.303       0.048
age            0.1062      0.010     10.328      0.000       0.086       0.126
fa            -0.0086      0.224     -0.039      0.969      -0.450       0.432
year_2009      0.5175      0.338      1.530      0.127      -0.148       1.183
year_2010      0.2129      0.333      0.640      0.523      -0.442       0.868
year_2012      0.3770      0.331      1.138      0.256      -0.275       1.029
year_2013      0.3236      0.333      0.973      0.332      -0.331       0.979
year_2014      0.1742      0.330      0.528      0.598      -0.476       0.824
year_2015      0.4323      0.336      1.288      0.199      -0.229       1.093
year_2016      0.2300      0.326      0.706      0.481      -0.412       0.872
year_2017      0.2460      0.323      0.761      0.447      -0.390       0.882
year_2018      0.5392      0.324      1.662      0.098      -0.099       1.178
year_2019      0.5071      0.309      1.640      0.102      -0.102       1.116
year_2020      0.6835      0.320      2.136      0.034       0.054       1.313
year_2021      0.5426      0.309      1.756      0.080      -0.066       1.151
year_2022      0.5209      0.307      1.695      0.091      -0.084       1.126
year_2023      0.6702      0.309      2.170      0.031       0.062       1.278
==============================================================================
Omnibus:                        3.535   Durbin-Watson:                   1.150
Prob(Omnibus):                  0.171   Jarque-Bera (JB):                3.223
Skew:                          -0.238   Prob(JB):                        0.200
Kurtosis:                       3.186   Cond. No.                     6.67e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.67e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

# PCA 구성 바꿔보기

In [10]:
# 오로지 성과만 구성 (IP)는 제거

group1_pure_perf = pd.DataFrame({
    "ERA": -df_log["ERA"],
    "FIP": -df_log["FIP"],
    "WHIP": -df_log["WHIP"],
    "K9":  df_log["K9"],
    "BB9": -df_log["BB9"]
})

In [11]:
# W 혹은 resid_w 포함한 성과 구성

group1_perf_w = pd.DataFrame({
    "ERA": -df_log["ERA"],
    "FIP": -df_log["FIP"],
    "WHIP": -df_log["WHIP"],
    "K9":  df_log["K9"],
    "BB9": -df_log["BB9"],
    "W": df_log["W"]    # 또는 "resid_W"
})

In [13]:
# IP 대신 RS 추가?

group1_with_rs = pd.DataFrame({
    "ERA": -df_log["ERA"],
    "FIP": -df_log["FIP"],
    "WHIP": -df_log["WHIP"],
    "K9":  df_log["K9"],
    "BB9": -df_log["BB9"],
    "RS": df_log["RS"]
})